services:
  - type: web
    name: whatsapp-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ACCESS_TOKEN
        sync: false
      - key: APP_ID
        sync: false
      - key: APP_SECRET
        sync: false
      - key: RECIPIENT_WAID
        sync: false
      - key: VERSION
        value: v18.0
      - key: PHONE_NUMBER_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false 